### ISSUE TITLE
Random word instead of nickname

### ISSUE THREAD

**Issue by FerdinandoLM** [bucciarati/poe-component-irc-plugin-tumblr#1]
On tumblr i see that instead of the user's nickname, it shows random words, presumably the latest used right before url.

**Comment by bucciarati** [comment]
Hi, this is an anonymity feature which you can disable by setting a channel's **hide_nicks** property to false.  Like this:

```
[ Tumblr, {
  '#channel': {
    blog: 'my-channel.tumblr.com',
    # ...
    hide_nicks: false,
  },
]
```

I'm updating the README to illustrate this.

_edited because initially I stated that it defaults to true_
It defaults to false, so if you see "random nicks" it means that someone has configured the bot in a way similar to:

```
[Tumblr, {
  '#channel': {
    blog: 'my-channel.tumblr.com',
    # ...
    hide_nicks: 'mapfile',
    nick_map: '/usr/share/dict/italian',
]
```

**Comment by bucciarati** [comment]
README has been updated with this information.
